//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touristic.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividad
    {
        public int idactividad { get; set; }
        public int sitio_idsitio { get; set; }
        public System.DateTime fechadecritica { get; set; }
        public string observacion { get; set; }
        public string turista_documento { get; set; }
        public decimal nota { get; set; }
    
        public virtual sitio sitio { get; set; }
        public virtual turista turista { get; set; }
    }
}
