//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Touristic.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class sitio
    {
        public sitio()
        {
            this.actividad = new HashSet<actividad>();
        }
    
        public int idsitio { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public System.TimeSpan entrada { get; set; }
        public System.TimeSpan salida { get; set; }
        public string gratuito { get; set; }
        public string exposicion_tipo { get; set; }
    
        public virtual ICollection<actividad> actividad { get; set; }
        public virtual exposicion exposicion { get; set; }
    }
}
